export const product = [
    {
       id:1,
       img:"/P-imgs/m7.png",
       link:"#"
    },
    {
       id:2,
       img:"/P-imgs/m2.jpg",
       link:"#"
    },
    {
       id:3,
       img:"/P-imgs/m3.jpg",
       link:"#"
    },
    {
       id:4,
       img:"/P-imgs/m4.jpg",
       link:"#"
    },
    {
       id:5,
       img:"/P-imgs/m5.jpg",
       link:"#"
    },
    {
       id:6,
       img:"/P-imgs/m6.jpg",
       link:"#"
    },
]